[package]
name = "inventorer_print"
version = "0.1.0"
authors = ["Francis Begyn <francis.begyn@gmail.com>"]
edition = "2018"

[dependencies]
barcoders = {version = "0.10.0", features = ['image']}
printpdf = "0.2.10"
image = "0.21.1"
structopt = "0.2.15"
regex = "1"
